const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2348135252741";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_14_09_10_19_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTg0LFxuICAgICAgICAxNjgsXG4gICAgICAgIDE0MCxcbiAgICAgICAgNCxcbiAgICAgICAgNCxcbiAgICAgICAgMTIwLFxuICAgICAgICAxMjEsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjA5LFxuICAgICAgICAxNzUsXG4gICAgICAgIDYyLFxuICAgICAgICAyMTYsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTk2LFxuICAgICAgICAyMDYsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMjUyLFxuICAgICAgICAxNTksXG4gICAgICAgIDQ3LFxuICAgICAgICAyMDQsXG4gICAgICAgIDE4LFxuICAgICAgICAxMzgsXG4gICAgICAgIDE1LFxuICAgICAgICAxNjIsXG4gICAgICAgIDM5LFxuICAgICAgICAyOCxcbiAgICAgICAgOCxcbiAgICAgICAgMTU2LFxuICAgICAgICAyMjUsXG4gICAgICAgIDI1MixcbiAgICAgICAgMjExLFxuICAgICAgICA4NFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjYsXG4gICAgICAgIDk4LFxuICAgICAgICAxMjUsXG4gICAgICAgIDksXG4gICAgICAgIDE0LFxuICAgICAgICA0NSxcbiAgICAgICAgMTMyLFxuICAgICAgICA4NCxcbiAgICAgICAgNDAsXG4gICAgICAgIDgzLFxuICAgICAgICA4OSxcbiAgICAgICAgMTI4LFxuICAgICAgICA1NSxcbiAgICAgICAgMTk1LFxuICAgICAgICAxMCxcbiAgICAgICAgMTg4LFxuICAgICAgICA0LFxuICAgICAgICAyNDYsXG4gICAgICAgIDU3LFxuICAgICAgICA1OCxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMTcsXG4gICAgICAgIDUzLFxuICAgICAgICAxMjcsXG4gICAgICAgIDEyOCxcbiAgICAgICAgOTEsXG4gICAgICAgIDQyLFxuICAgICAgICA2LFxuICAgICAgICA0MyxcbiAgICAgICAgMjMyLFxuICAgICAgICAzMyxcbiAgICAgICAgNThcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1MixcbiAgICAgICAgMjMyLFxuICAgICAgICAxMzksXG4gICAgICAgIDIyOCxcbiAgICAgICAgOTUsXG4gICAgICAgIDg2LFxuICAgICAgICAyNTMsXG4gICAgICAgIDc4LFxuICAgICAgICAyNyxcbiAgICAgICAgNTEsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMjE1LFxuICAgICAgICA2MSxcbiAgICAgICAgMTgyLFxuICAgICAgICA0LFxuICAgICAgICAyMTAsXG4gICAgICAgIDcwLFxuICAgICAgICAyMTcsXG4gICAgICAgIDI2LFxuICAgICAgICAyMDEsXG4gICAgICAgIDI0NixcbiAgICAgICAgNzMsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTQ3LFxuICAgICAgICAzOCxcbiAgICAgICAgMTAxLFxuICAgICAgICA3MyxcbiAgICAgICAgMTUsXG4gICAgICAgIDk3LFxuICAgICAgICAxMDQsXG4gICAgICAgIDEwNyxcbiAgICAgICAgOTVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOTUsXG4gICAgICAgIDE3OCxcbiAgICAgICAgNjAsXG4gICAgICAgIDIyMixcbiAgICAgICAgMjE1LFxuICAgICAgICAyMDUsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMjI0LFxuICAgICAgICA5NSxcbiAgICAgICAgMTY5LFxuICAgICAgICAxMTAsXG4gICAgICAgIDI4LFxuICAgICAgICAxOTgsXG4gICAgICAgIDQ1LFxuICAgICAgICAxMixcbiAgICAgICAgMjcsXG4gICAgICAgIDU3LFxuICAgICAgICAyNTUsXG4gICAgICAgIDQ5LFxuICAgICAgICAyMDQsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMjMyLFxuICAgICAgICAxNzAsXG4gICAgICAgIDYyLFxuICAgICAgICA2NCxcbiAgICAgICAgMTc4LFxuICAgICAgICAxMjksXG4gICAgICAgIDIxLFxuICAgICAgICAyMzcsXG4gICAgICAgIDk5LFxuICAgICAgICAxMDgsXG4gICAgICAgIDEwOFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUyLFxuICAgICAgICA1MixcbiAgICAgICAgODEsXG4gICAgICAgIDE4MixcbiAgICAgICAgMCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxNjAsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjE5LFxuICAgICAgICAyNDIsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjAyLFxuICAgICAgICA2NixcbiAgICAgICAgMjE1LFxuICAgICAgICAyNDMsXG4gICAgICAgIDc5LFxuICAgICAgICAyMyxcbiAgICAgICAgODcsXG4gICAgICAgIDI0MyxcbiAgICAgICAgODQsXG4gICAgICAgIDk3LFxuICAgICAgICAyMzUsXG4gICAgICAgIDMwLFxuICAgICAgICAyMzYsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTY2LFxuICAgICAgICAxMDcsXG4gICAgICAgIDM2LFxuICAgICAgICA4OSxcbiAgICAgICAgMzksXG4gICAgICAgIDYsXG4gICAgICAgIDk0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIwNixcbiAgICAgICAgMjYsXG4gICAgICAgIDY3LFxuICAgICAgICAxODQsXG4gICAgICAgIDE2NSxcbiAgICAgICAgNDIsXG4gICAgICAgIDM2LFxuICAgICAgICA2NCxcbiAgICAgICAgMTI0LFxuICAgICAgICAxODgsXG4gICAgICAgIDU3LFxuICAgICAgICAyMzUsXG4gICAgICAgIDYxLFxuICAgICAgICAxODAsXG4gICAgICAgIDE1NCxcbiAgICAgICAgNDksXG4gICAgICAgIDg5LFxuICAgICAgICA2MCxcbiAgICAgICAgOTQsXG4gICAgICAgIDk1LFxuICAgICAgICAxODMsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTAsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTMyLFxuICAgICAgICAxODAsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMjYsXG4gICAgICAgIDIwOCxcbiAgICAgICAgODksXG4gICAgICAgIDU4LFxuICAgICAgICA0OFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgMjUyLFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAzMyxcbiAgICAgICAgICA4NFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMSxcbiAgICAgICAgICAyMixcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMixcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAxMDJcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMjIsXG4gICAgICAgIDYzLFxuICAgICAgICAxMCxcbiAgICAgICAgMTU0LFxuICAgICAgICAxNjYsXG4gICAgICAgIDc0LFxuICAgICAgICAyMCxcbiAgICAgICAgMyxcbiAgICAgICAgNixcbiAgICAgICAgMTI1LFxuICAgICAgICA1NCxcbiAgICAgICAgMTAzLFxuICAgICAgICAyNTMsXG4gICAgICAgIDQyLFxuICAgICAgICAxOTEsXG4gICAgICAgIDE0NCxcbiAgICAgICAgNTksXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTY2LFxuICAgICAgICAyMzMsXG4gICAgICAgIDAsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTE3LFxuICAgICAgICAyMTksXG4gICAgICAgIDEyMSxcbiAgICAgICAgMTA2LFxuICAgICAgICAzOCxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxMzUsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTY5LFxuICAgICAgICAxNTgsXG4gICAgICAgIDcwLFxuICAgICAgICAyNTUsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTc2LFxuICAgICAgICAxMzEsXG4gICAgICAgIDI1LFxuICAgICAgICA3NCxcbiAgICAgICAgMTYzLFxuICAgICAgICAxMDEsXG4gICAgICAgIDE5MixcbiAgICAgICAgMTcxLFxuICAgICAgICA2MixcbiAgICAgICAgMTMzLFxuICAgICAgICAzMSxcbiAgICAgICAgMTc0LFxuICAgICAgICAzMSxcbiAgICAgICAgNTQsXG4gICAgICAgIDQ1LFxuICAgICAgICAxMTksXG4gICAgICAgIDIwNSxcbiAgICAgICAgMjEzLFxuICAgICAgICAxOTAsXG4gICAgICAgIDcsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMjA5LFxuICAgICAgICA2OSxcbiAgICAgICAgMjksXG4gICAgICAgIDUsXG4gICAgICAgIDExNixcbiAgICAgICAgMTIsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTI5XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxMjksXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiVXlQWkh0YVl3K0p4TW5qM3VsaTNaa3gvUHlia2d2Wng0bE16VC9BWHpEZz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ4MTM1MjUyNzQxQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIwMUZEQTc2MEVFNkFEM0M4RTI4Q0MwQjAzNjAzMjU1M1wiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjkzNDY5ODNcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiYi1nQ2s2ZnpScy1jSzZvb2tyczlfZ1wiLFxuICBcInBob25lSWRcIjogXCJjMTBiZGNkMy1hNGI1LTRlYzEtOTU1ZS1jMTRiMDAxMTA0NjZcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNTcsXG4gICAgICA1MixcbiAgICAgIDEwNCxcbiAgICAgIDE1NyxcbiAgICAgIDEzLFxuICAgICAgMjQwLFxuICAgICAgMjAxLFxuICAgICAgMjE1LFxuICAgICAgMTA4LFxuICAgICAgMTU5LFxuICAgICAgMjEwLFxuICAgICAgMTQ1LFxuICAgICAgOTUsXG4gICAgICAxNTMsXG4gICAgICAyNyxcbiAgICAgIDIyMSxcbiAgICAgIDE2NyxcbiAgICAgIDU5LFxuICAgICAgMTI2LFxuICAgICAgMTA0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDI0OSxcbiAgICAgIDY5LFxuICAgICAgMzMsXG4gICAgICAxOTIsXG4gICAgICA3NyxcbiAgICAgIDU1LFxuICAgICAgNDcsXG4gICAgICAxNzksXG4gICAgICAxMjksXG4gICAgICAxNjAsXG4gICAgICAxNzksXG4gICAgICAxNjEsXG4gICAgICAyMTQsXG4gICAgICAyNTQsXG4gICAgICAyMjEsXG4gICAgICAxNzYsXG4gICAgICA0NyxcbiAgICAgIDE2MSxcbiAgICAgIDQ4LFxuICAgICAgMTMyXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIlRFNkc5R0Y4XCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ4MTM1MjUyNzQxOjdAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjEyNDk4NzQwNzQ0NDIxOjdAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDUHk2eklRQkVLRDd6cmdHR0FRZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJJTHJza1JENlpSV2llSFR1R05Ia2Q5bzVLMVY5dUhHbTRnWkh3S3lZVTBBPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInIrblVLWndvY1lLYTMzc3VzUFdPVTB5aEM2WEFVSndZeUlWeWdzTDhFSEJpUEYwbExDbDliOUIreFA3c2Z4UldpNisyTTZnZ1V3ZzNMa293aWdlRUFBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcInNpTVpYZTBuM0FQUzZJNVl1QUdZa0xnMzRWTDZ0RytsNlNkdE5yRkd1S2N4aTlVM2plQmJGTHk2M1paZ0F0VDVnYkp6Q0M3ZmpYZi9QVCthaWxsUmpRPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDgxMzUyNTI3NDE6N0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDEyMCxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDYsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICAxNTIsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgNjRcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyOTM0Njk4MCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUZmV1wiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRmZXLmpzb24iOiAie1wia2V5RGF0YVwiOlwiSlBOWGlHenZXU0R1eEw3NTNJaW1jbW9QUU1HSjYxYmJSQnlLRmZMTEtobz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyNzgwNzY3OTYsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyODQ3Njg5MzEyMFwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
